# Generated by Django 3.0.5 on 2020-04-02 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('u_id', models.IntegerField(default=330138)),
                ('post_type', models.CharField(choices=[('B', 'boast'), ('R', 'roast')], max_length=1)),
                ('text', models.CharField(max_length=280)),
                ('up', models.IntegerField(default=0)),
                ('down', models.IntegerField(default=0)),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
